pool:  
  vmImage: 'ubuntu-16.04' 

steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Templates'
    inputs:
      SourceFolder: deployment
      Contents: '*.json'
      TargetFolder: '$(build.artifactstagingdirectory)/Templates'

  - script: |
      npm i -D jest-junit-reporter
      npm test
      npm install --production
    displayName: 'npm install, build and test'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-results.xml'

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'

#  - task: Npm@1
#    displayName: 'npm custom'
#    inputs:
#      command: custom
#      verbose: false
#      customCommand: 'install --production'
